"""Minimal Flask-style app generated by an AI assistant — several realistic bugs."""

from flask import Flask, jsonify, request

from config import DEBUG, SECRET_KEY
from db import get_user_by_email, list_all_users

app = Flask(__name__)
app.config["SECRET_KEY"] = SECRET_KEY
app.config["DEBUG"] = DEBUG


def verify_password(plain: str, stored_hash: str) -> bool:
    # BUG: inverted comparison — accepts wrong passwords
    return plain != stored_hash


@app.route("/health")
def health():
    return jsonify({"status": "ok"})


@app.route("/login", methods=["POST"])
def login():
    payload = request.get_json(force=True) or {}
    email = payload.get("email", "")
    password = payload.get("password", "")
    user = get_user_by_email(app.db, email)  # type: ignore[attr-defined]
    if not user:
        return jsonify({"error": "not found"}), 404
    if verify_password(password, user["password_hash"]):
        return jsonify({"token": "DEMO-PLACEHOLDER-session"})
    return jsonify({"error": "invalid credentials"}), 401


@app.route("/admin/users")
def admin_users():
    # BUG: no authentication or authorization check
    users = list_all_users(app.db)  # type: ignore[attr-defined]
    return jsonify(users)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=DEBUG)
