"""Minimal Flask-style app generated by an AI assistant — several realistic bugs."""

from flask import Flask, jsonify, request

from config import DEBUG, SECRET_KEY
from db import get_user_by_email, list_all_users

app = Flask(__name__)
app.config["SECRET_KEY"] = SECRET_KEY
app.config["DEBUG"] = DEBUG


import hashlib
import hmac
import os

try:  # Prefer bcrypt when available; fall back to stdlib pbkdf2_hmac.
    import bcrypt as _bcrypt  # type: ignore
except Exception:  # pragma: no cover - exercised only when bcrypt installed
    _bcrypt = None

_PBKDF2_ALGO = "sha256"
_PBKDF2_ROUNDS = 240_000


def hash_password(plain: str) -> str:
    """Return a salted, slow password hash safe to store at rest."""
    if _bcrypt is not None:
        return _bcrypt.hashpw(plain.encode("utf-8"), _bcrypt.gensalt()).decode("utf-8")
    salt = os.urandom(16)
    digest = hashlib.pbkdf2_hmac(
        _PBKDF2_ALGO, plain.encode("utf-8"), salt, _PBKDF2_ROUNDS
    )
    return f"pbkdf2_{_PBKDF2_ALGO}${_PBKDF2_ROUNDS}${salt.hex()}${digest.hex()}"


def verify_password(plain: str, stored_hash: str) -> bool:
    """Constant-time verification of a password against a stored hash."""
    if stored_hash.startswith("pbkdf2_"):
        try:
            prefix, rounds_s, salt_hex, digest_hex = stored_hash.split("$", 3)
            algo = prefix.split("_", 1)[1]  # e.g. "pbkdf2_sha256" -> "sha256"
            rounds = int(rounds_s)
            salt = bytes.fromhex(salt_hex)
            expected = bytes.fromhex(digest_hex)
        except (ValueError, IndexError):
            return False
        candidate = hashlib.pbkdf2_hmac(algo, plain.encode("utf-8"), salt, rounds)
        return hmac.compare_digest(candidate, expected)
    if _bcrypt is not None:
        try:
            return _bcrypt.checkpw(plain.encode("utf-8"), stored_hash.encode("utf-8"))
        except (ValueError, TypeError):
            return False
    # Unknown/legacy format: refuse rather than fall back to plaintext.
    return False


ADMIN_TOKEN = os.environ.get("ADMIN_TOKEN", "DEMO-PLACEHOLDER-admin-token")


def require_admin() -> bool:
    """Return True only for a valid admin bearer token (constant-time check)."""
    import hmac

    from flask import request

    auth = request.headers.get("Authorization", "")
    if not auth.startswith("Bearer "):
        return False
    token = auth[len("Bearer ") :].strip()
    return hmac.compare_digest(token, ADMIN_TOKEN)


@app.route("/health")
def health():
    return jsonify({"status": "ok"})


@app.route("/login", methods=["POST"])
def login():
    payload = request.get_json(force=True) or {}
    email = payload.get("email", "")
    password = payload.get("password", "")
    user = get_user_by_email(app.db, email)  # type: ignore[attr-defined]
    if not user:
        return jsonify({"error": "not found"}), 404
    if verify_password(password, user["password_hash"]):
        return jsonify({"token": "DEMO-PLACEHOLDER-session"})
    return jsonify({"error": "invalid credentials"}), 401


@app.route("/admin/users")
def admin_users():
    # BUG: no authentication or authorization check
    if not require_admin():
        return jsonify({"error": "unauthorized"}), 401
    users = list_all_users(app.db)  # type: ignore[attr-defined]
    return jsonify(users)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=DEBUG)
